name: Setup Environment
description: Setup Rust, Solana CLI, and optionally Node.js for testing

inputs:
  node-version:
    description: "Node.js version to install (optional)"
    required: false
    default: ""
  node-version-default:
    description: "Default Node.js version for Light CLI"
    required: false
    default: "22"
  solana-cli-version:
    description: "Solana CLI version"
    required: false
    default: "2.3.11"
  rust-toolchain:
    description: "Rust toolchain version"
    required: false
    default: "1.90.0"

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.rust-toolchain }}

    - name: Setup Node.js
      if: inputs.node-version != ''
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Node.js (for Light CLI)
      if: inputs.node-version == ''
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version-default }}

    - name: Cache Solana CLI tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/solana/
          ~/.local/share/solana/
        key: solana-cli-${{ runner.os }}-build-${{ inputs.solana-cli-version }}

    - name: Install Solana CLI tools
      shell: bash
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v${{ inputs.solana-cli-version }}/install)"
        echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Install Light CLI
      shell: bash
      run: npm install -g @lightprotocol/zk-compression-cli@0.27.1-alpha.2

    - name: Generate keypair
      shell: bash
      run: solana-keygen new --no-bip39-passphrase

    - name: Display versions
      shell: bash
      run: |
        rustc --version
        cargo --version
        solana --version
        light --version
        if [ -n "${{ inputs.node-version }}" ]; then
          node --version
          npm --version
        fi
